# Generated by Django 5.2 on 2025-05-24 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='foul name')),
                ('short_name', models.CharField(max_length=5, verbose_name='foul short name')),
            ],
            options={
                'verbose_name': 'foul',
                'verbose_name_plural': 'fouls',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team_score', models.PositiveIntegerField(blank=True, default=0, verbose_name='home team score')),
                ('away_team_score', models.PositiveIntegerField(blank=True, default=0, verbose_name='away team score')),
                ('date', models.DateTimeField(blank=True, verbose_name='game time')),
                ('video_link', models.URLField(blank=True, verbose_name="link to game's videos")),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='league name')),
            ],
            options={
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('season_name', models.CharField(max_length=50, verbose_name='season name')),
            ],
            options={
                'verbose_name': 'season',
                'verbose_name_plural': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, verbose_name='team name')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Game_Foul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1 QTR', 'First Quarter'), ('2 QTR', 'Second Quarter'), ('3 QTR', 'Third Quarter'), ('4 QTR', 'Fourth Quarter'), ('OT', 'Overtime')], default='1 QTR', max_length=5, verbose_name='period')),
                ('foul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.foul', verbose_name='foul')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'game foul',
                'verbose_name_plural': 'game fouls',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='fouls_in_game',
            field=models.ManyToManyField(through='football.Game_Foul', to='football.foul'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.league', verbose_name='league'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.season', verbose_name='season'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_game_set', to='football.team', verbose_name='away team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_game_set', to='football.team', verbose_name='home team'),
        ),
    ]
