# Generated by Django 5.2 on 2025-04-25 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Foul name:', max_length=100, verbose_name='foul name')),
                ('short_name', models.CharField(help_text='Enter the Foul short name:', max_length=5, verbose_name='foul short name')),
            ],
            options={
                'verbose_name': 'foul',
                'verbose_name_plural': 'fouls',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text='Select the game time:', verbose_name='game time')),
                ('video_link', models.URLField(blank=True, help_text="Enter the link for the game's video:", verbose_name="link to game's videos")),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the League name:', max_length=100, verbose_name='league name')),
            ],
            options={
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(help_text='Enter the Season name: ', max_length=50, verbose_name='season name')),
            ],
            options={
                'verbose_name': 'season',
                'verbose_name_plural': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Enter the Team name:', max_length=100, verbose_name='team name')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Game_Foul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1 QTR', 'First Quarter'), ('2 QTR', 'Second Quarter'), ('3 QTR', 'Third Quarter'), ('4 QTR', 'Fourth Quarter'), ('OT', 'Overtime')], default='1 QTR', help_text='Enter the period when the foul happend:', max_length=5, verbose_name='period')),
                ('foul', models.ForeignKey(help_text='Enter the foul:', on_delete=django.db.models.deletion.PROTECT, to='football.foul', verbose_name='foul')),
                ('game', models.ForeignKey(help_text='Enter the game where the foul happend:', on_delete=django.db.models.deletion.PROTECT, to='football.game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'game foul',
                'verbose_name_plural': 'game fouls',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='fouls_in_game',
            field=models.ManyToManyField(through='football.Game_Foul', to='football.foul'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(help_text="Enter this game's league:", on_delete=django.db.models.deletion.PROTECT, to='football.league', verbose_name='league'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(help_text='Select the game season', on_delete=django.db.models.deletion.PROTECT, to='football.season', verbose_name='season'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(help_text='Select the away Team:', on_delete=django.db.models.deletion.PROTECT, related_name='away_game_set', to='football.team', verbose_name='away team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(help_text='Select the home Team:', on_delete=django.db.models.deletion.PROTECT, related_name='home_game_set', to='football.team', verbose_name='home team'),
        ),
    ]
