# Generated by Django 5.2 on 2025-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
