# Generated by Django 5.2 on 2025-05-26 21:22

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def create_foul_objects(apps, __):
    Foul = apps.get_model("football", "Foul")

    Foul(name=_(""), short_name="", enabled=True).save()
    Foul(name=_(""), short_name="", enabled=True).save()


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_foul_objects),
    ]
