# Generated by Django 5.2 on 2025-05-24 21:04

from django.db import migrations


def create_foul_objects(apps, _):
    Foul = apps.get_model("football", "Foul")

    Foul(name="", short_name="").save()
    Foul(name="", short_name="").save()


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0002_alter_game_date"),
    ]

    operations = [
        migrations.RunPython(create_foul_objects),
    ]
